# Theme
include vague.conf

# Font
font_family JetBrainsMono Nerd Font Mono
font_size 10

# Window appearance
hide_window_decorations yes
window_padding_width 10
tab_bar_style powerline
background_opacity 1.0

# Window behavior
confirm_os_window_close 0

shell_integration enabled
