# Minimal vague prompt
format = "$directory$git_branch$git_status$character"

[directory]
style = "bold #6e94b2"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
style = "#7fa563"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#606079"
format = "[$all_status$ahead_behind]($style) "

[character]
success_symbol = "[❯](bold #cdcdcd)"
error_symbol = "[❯](#d8647e)"
vimcmd_symbol = "[❮](#cdcdcd)"
