# Minimal oxocarbon prompt
format = "$directory$git_branch$git_status$character"

[directory]
style = "bold #f2f2f2"
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = ""
style = "#78a9ff"
format = "on [$symbol$branch]($style) "

[git_status]
style = "#525252"
format = "[$all_status$ahead_behind]($style) "

[character]
success_symbol = "[❯](bold #78a9ff)"
error_symbol = "[❯](#ee5396)"
vimcmd_symbol = "[❮](#78a9ff)"
