pragma Singleton
import QtQuick
import Quickshell
import Quickshell.Io
import "SettingsUtil.js" as U

Singleton {
    id: settings

    property string wallpaperOverride: ""
    property var wallpapers: []

    property real sensitivity: 0
    property real touchScroll: 0.8
    property bool naturalScroll: true

    property int dimTimeout: 150
    property int lockTimeout: 300
    property int screenOffTimeout: 330
    property int suspendTimeout: 1800

    property int lowBatteryPct: 20
    property int criticalBatteryPct: 10
    property string criticalBatteryAction: "notify"
    property string lidCloseAction: "suspend"
    property string powerProfileOnBattery: "keep"

    property bool loaded: false
    property string lastApplyMsg: ""
    property var applyQueue: []

    readonly property string settingsFile: {
        const xdg = Quickshell.env("XDG_DATA_HOME") ?? "";
        const home = Quickshell.env("HOME") ?? "";
        const base = xdg !== "" ? xdg : (home !== "" ? home + "/.local/share" : "/tmp/.local/share");
        return base + "/quickshell/settings.json";
    }
    readonly property string hypridleFile: {
        const home = Quickshell.env("HOME") ?? "";
        return (home !== "" ? home : "/tmp") + "/.config/hypr/hypridle.conf";
    }
    readonly property string monitorsLuaFile: {
        const xdg = Quickshell.env("XDG_DATA_HOME") ?? "";
        const home = Quickshell.env("HOME") ?? "";
        const base = xdg !== "" ? xdg : (home !== "" ? home + "/.local/share" : "/tmp/.local/share");
        return base + "/quickshell/qs-monitors.lua";
    }

    function monitorsLua(): string {
        const lines = ["-- Generated by quickshell display settings. Do not edit manually."];
        for (const name of Object.keys(settings.monitorConfigs))
            lines.push(settings.monitorRuleCode(name));
        return lines.join("\n") + "\n";
    }

    function snapshot(): var {
        return {
            wallpaperOverride: settings.wallpaperOverride,
            sensitivity: settings.sensitivity,
            touchScroll: settings.touchScroll,
            naturalScroll: settings.naturalScroll,
            dimTimeout: settings.dimTimeout,
            lockTimeout: settings.lockTimeout,
            screenOffTimeout: settings.screenOffTimeout,
            suspendTimeout: settings.suspendTimeout,
            lowBatteryPct: settings.lowBatteryPct,
            criticalBatteryPct: settings.criticalBatteryPct,
            criticalBatteryAction: settings.criticalBatteryAction,
            lidCloseAction: settings.lidCloseAction,
            powerProfileOnBattery: settings.powerProfileOnBattery,
            mainMonitor: settings.mainMonitor,
            monitorConfigs: settings.monitorConfigs
        };
    }

    function applyLoaded(obj): void {
        if (!obj || typeof obj !== "object")
            return;
        settings.wallpaperOverride = U.pickStr(obj.wallpaperOverride, "");
        settings.sensitivity = U.num(obj.sensitivity, 0, -1, 1);
        settings.touchScroll = U.num(obj.touchScroll, 0.8, 0.1, 2);
        settings.naturalScroll = U.pickBool(obj.naturalScroll, true);
        settings.dimTimeout = Math.round(U.num(obj.dimTimeout, 150, 0, 600));
        settings.lockTimeout = Math.round(U.num(obj.lockTimeout, 300, 0, 3600));
        settings.screenOffTimeout = Math.round(U.num(obj.screenOffTimeout, 330, 0, 3600));
        settings.suspendTimeout = Math.round(U.num(obj.suspendTimeout, 1800, 0, 7200));
        settings.lowBatteryPct = Math.round(U.num(obj.lowBatteryPct, 20, 5, 50));
        settings.criticalBatteryPct = Math.min(Math.round(U.num(obj.criticalBatteryPct, 10, 3, 30)), settings.lowBatteryPct);
        settings.criticalBatteryAction = U.pickOpt(obj.criticalBatteryAction, "notify", ["suspend", "hibernate", "poweroff", "lock", "notify"]);
        settings.lidCloseAction = U.pickOpt(obj.lidCloseAction, "suspend", ["suspend", "lock", "ignore"]);
        settings.powerProfileOnBattery = U.pickOpt(obj.powerProfileOnBattery, "keep", ["keep", "powersaver", "balanced", "performance"]);
        settings.mainMonitor = U.pickStr(obj.mainMonitor, "auto");
        settings.enforceIdleOrder();
        if (obj.monitorConfigs && typeof obj.monitorConfigs === "object") {
            const clean = {};
            for (const name of Object.keys(obj.monitorConfigs)) {
                if (typeof name !== "string" || name === "")
                    continue;
                const e = obj.monitorConfigs[name];
                if (!e || typeof e !== "object")
                    continue;
                const entry = {};
                if (typeof e.enabled === "boolean")
                    entry.enabled = e.enabled;
                if (typeof e.scale === "number" && !isNaN(e.scale))
                    entry.scale = Math.max(0.5, Math.min(3, e.scale));
                if (typeof e.res === "string" && e.res !== "")
                    entry.res = e.res.slice(0, 64);
                if (typeof e.pos === "string" && U.isValidMonitorPos(e.pos))
                    entry.pos = e.pos.slice(0, 64);
                clean[name] = entry;
            }
            settings.monitorConfigs = clean;
        }
    }

    function applyAll(): void {
        HyprBridge.hypr("input:sensitivity", String(settings.sensitivity));
        HyprBridge.hypr("input:touchpad:scroll_factor", String(settings.touchScroll));
        HyprBridge.hypr("input:touchpad:natural_scroll", settings.naturalScroll ? "true" : "false");
        Wallpaper.applyOverride(settings.wallpaperOverride);
    }
    function applyScannedMonitors(): void {
        if (!settings.monitorsReady || !settings.loaded)
            return;
        settings.migrateKeywordPositions();
        const pending = Object.keys(settings.monitorConfigs).filter(name => !settings.appliedMonitors.includes(name) && settings.monitorLive(name) !== null);
        if (pending.length === 0)
            return;
        pending.sort((a, b) => {
            const la = settings.monitorLive(a) ?? {};
            const lb = settings.monitorLive(b) ?? {};
            return (la.x ?? 0) - (lb.x ?? 0) || (la.y ?? 0) - (lb.y ?? 0);
        });
        const targets = [];
        for (const name of pending) {
            if (!settings.monitorEnabled(name) && !settings.canDisableMonitor(name)) {
                settings.putMonitorCfg(name, {enabled: true});
                settings.lastApplyMsg = name + " kept enabled (only display)";
                settings.scheduleSave();
            }
            settings.appliedMonitors = [...settings.appliedMonitors, name];
            targets.push(name);
        }
        settings.applyBatched(targets.map(n => settings.monitorRuleDesc(n)).join(", "), targets.map(n => settings.monitorRuleCode(n)), true, targets);
    }
    function migrateKeywordPositions(): void {
        if (!settings.monitorsReady || !settings.loaded)
            return;
        const live = settings.monitors.filter(m => m && typeof m.name === "string" && m.name !== "" && settings.monitorEnabled(m.name));
        if (live.length === 0)
            return;
        let stale = false;
        let axis = "row";
        for (const m of live) {
            const p = settings.monitorPos(m.name);
            if (p !== "auto" && !U.isExplicitPos(p))
                stale = true;
            if (p === "auto-down" || p === "auto-up")
                axis = "column";
        }
        if (!stale)
            return;
        const byAxis = axis === "column" ? (a, b) => (a.y ?? 0) - (b.y ?? 0) : (a, b) => (a.x ?? 0) - (b.x ?? 0);
        const ordered = live.slice().sort(byAxis).map(m => String(m.name));
        const map = settings.layoutCoords(ordered, axis);
        for (const n of Object.keys(map))
            settings.putMonitorCfg(n, {pos: map[n]});
        settings.scheduleSave();
    }
    function reapplyAfterReload(): void {
        if (!settings.loaded)
            return;
        settings.applyAll();
        for (const name of Object.keys(settings.monitorConfigs)) {
            if (settings.monitorLive(name) !== null)
                settings.applyMonitor(name, true, true);
        }
        settings.refreshMonitors(true);
    }

    function setWallpaper(path: string): void {
        if (typeof path !== "string" || path === "")
            return;
        settings.wallpaperOverride = path;
        Wallpaper.applyOverride(path);
        settings.scheduleSave();
    }
    function ensureWallpaper(): void {
        if (settings.wallpaperOverride === "" && settings.wallpapers.length > 0) {
            settings.wallpaperOverride = settings.wallpapers[0];
            Wallpaper.applyOverride(settings.wallpaperOverride);
            settings.scheduleSave();
        }
    }
    property double lastWallScan: 0
    property double lastMonScan: 0
    function refreshWallpapers(force: bool): void {
        if (wallpaperScan.running)
            return;
        if (!force && Date.now() - settings.lastWallScan < 30000)
            return;
        settings.lastWallScan = Date.now();
        wallpaperScan.running = true;
    }

    function setSensitivity(v: real): void {
        settings.sensitivity = Math.round(Math.max(-1, Math.min(1, v)) * 10) / 10;
        HyprBridge.hypr("input:sensitivity", String(settings.sensitivity));
        settings.scheduleSave();
    }
    function setTouchScroll(v: real): void {
        settings.touchScroll = Math.round(Math.max(0.1, Math.min(2, v)) * 10) / 10;
        HyprBridge.hypr("input:touchpad:scroll_factor", String(settings.touchScroll));
        settings.scheduleSave();
    }
    function setNaturalScroll(on: bool): void {
        settings.naturalScroll = on;
        HyprBridge.hypr("input:touchpad:natural_scroll", on ? "true" : "false");
        settings.scheduleSave();
    }

    function refreshMonitors(force: bool): void {
        if (monitorScan.running)
            return;
        if (!force && Date.now() - settings.lastMonScan < 30000)
            return;
        settings.lastMonScan = Date.now();
        monitorScan.running = true;
    }
    function monitorCfg(name: string): var {
        return settings.monitorConfigs[name] ?? {};
    }
    function monitorLive(name: string): var {
        return settings.monitors.find(m => m && m.name === name) ?? null;
    }
    function monitorEnabled(name: string): bool {
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.enabled === "boolean")
            return cfg.enabled;
        const live = settings.monitorLive(name);
        return live ? live.disabled !== true : true;
    }
    function enabledMonitors(): var {
        return settings.monitors.filter(m => m && settings.monitorEnabled(m.name));
    }
    function canDisableMonitor(name: string): bool {
        if (!settings.monitorsReady)
            return false;
        const enabled = settings.enabledMonitors();
        if (enabled.length === 0)
            return true;
        if (enabled.length > 1)
            return true;
        return enabled[0].name !== name;
    }
    function monitorScale(name: string): real {
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.scale === "number" && !isNaN(cfg.scale))
            return Math.max(0.5, Math.min(3, cfg.scale));
        const live = settings.monitorLive(name);
        return live && typeof live.scale === "number" ? live.scale : 1;
    }
    function monitorModes(name: string): var {
        const modes = ["preferred"];
        const live = settings.monitorLive(name);
        if (live && Array.isArray(live.availableModes)) {
            for (const m of live.availableModes) {
                if (typeof m === "string" && m !== "" && !modes.includes(m))
                    modes.push(m);
            }
        }
        return U.dedupeSortModes(modes);
    }
    function monitorResolutions(name: string): var {
        return ["Preferred"].concat(U.resolutionsFor(settings.monitorModes(name)));
    }
    function monitorResKey(name: string): string {
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.res === "string" && cfg.res !== "" && cfg.res !== "preferred")
            return U.resKeyOf(cfg.res);
        return "Preferred";
    }
    function monitorDetails(name: string): string {
        return U.monitorDetails(settings.monitorLive(name));
    }
    function monitorRes(name: string): string {
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.res === "string" && cfg.res !== "")
            return cfg.res;
        const live = settings.monitorLive(name);
        if (live && typeof live.width === "number" && typeof live.height === "number") {
            if (typeof live.refreshRate === "number")
                return live.width + "x" + live.height + "@" + live.refreshRate.toFixed(2) + "Hz";
            return live.width + "x" + live.height;
        }
        return "preferred";
    }
    function monitorSummary(name: string): string {
        const live = settings.monitorLive(name);
        if (!live || typeof live.width !== "number" || typeof live.height !== "number")
            return name;
        const rate = typeof live.refreshRate === "number" ? live.refreshRate.toFixed(2) : "?";
        let s = name + "  " + live.width + "x" + live.height + "@" + rate + "  x" + settings.monitorScale(name).toFixed(2).replace(/\.?0+$/, "");
        const pos = settings.monitorPos(name);
        if (pos !== "auto" && settings.enabledMonitors().length > 1)
            s += "  " + U.posLabel(pos);
        if (!settings.monitorEnabled(name) || live.disabled === true)
            s += "  (disabled)";
        else if (!settings.canDisableMonitor(name))
            s += "  (last display)";
        return s;
    }
    function monitorRuleCode(name: string): string {
        if (!settings.monitorEnabled(name))
            return 'hl.monitor({output = ' + HyprBridge.luaStr(name) + ', disabled = true})';
        const scale = HyprBridge.luaVal(String(settings.monitorScale(name)));
        const res = String(settings.monitorRes(name));
        const pos = settings.monitorPos(name);
        return 'hl.monitor({output = ' + HyprBridge.luaStr(name) + ', disabled = false, mode = ' + HyprBridge.luaStr(res) + ', position = ' + HyprBridge.luaStr(pos) + ', scale = ' + scale + '})';
    }
    function monitorRuleDesc(name: string): string {
        if (!settings.monitorEnabled(name))
            return name + " disabled";
        const pos = settings.monitorPos(name);
        return name + " -> " + String(settings.monitorRes(name)) + " x" + String(settings.monitorScale(name)) + (pos !== "auto" ? " " + pos : "");
    }
    function applyMonitor(name: string, quiet: bool, force: bool): void {
        const q = !!quiet;
        if (typeof name !== "string" || name === "" || name.length > 128)
            return;
        const live = settings.monitorLive(name);
        if (!force && live && settings.monitorInSync(name, live)) {
            settings.lastApplyMsg = name + " already in sync";
            return;
        }
        if (!q && !settings.appliedMonitors.includes(name))
            settings.appliedMonitors = [...settings.appliedMonitors, name];
        if (!settings.monitorEnabled(name)) {
            if (!settings.canDisableMonitor(name)) {
                settings.putMonitorCfg(name, {enabled: true});
                settings.lastApplyMsg = name + " kept enabled (only display)";
                settings.scheduleSave();
                return;
            }
            settings.applyTracked(settings.monitorRuleDesc(name), settings.monitorRuleCode(name), q, name);
            return;
        }
        settings.applyTracked(settings.monitorRuleDesc(name), settings.monitorRuleCode(name), q, name);
    }
    function monitorInSync(name: string, live: var): bool {
        if (!live)
            return false;
        if (settings.monitorEnabled(name) !== (live.disabled !== true))
            return false;
        if (!settings.monitorEnabled(name))
            return true;
        if (typeof live.scale !== "number" || Math.abs(live.scale - settings.monitorScale(name)) > 0.001)
            return false;
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.res === "string" && cfg.res !== "" && cfg.res !== "preferred") {
            if (cfg.res !== U.liveModeStr(live))
                return false;
        }
        const pos = settings.monitorPos(name);
        if (pos !== "auto") {
            const pp = U.parsePos(pos);
            if (pp === null)
                return false;
            if (live.x !== pp.x || live.y !== pp.y)
                return false;
        }
        return true;
    }
    function monitorPos(name: string): string {
        const cfg = settings.monitorCfg(name);
        if (typeof cfg.pos === "string" && U.isValidMonitorPos(cfg.pos))
            return cfg.pos;
        return "auto";
    }
    function effSize(name: string): var {
        const d = settings.scaleDims(name);
        const s = settings.monitorScale(name) || 1;
        return {w: Math.max(1, Math.round(d.w / s)), h: Math.max(1, Math.round(d.h / s))};
    }
    function layoutCoords(order: var, axis: string): var {
        const map = {};
        const list = Array.isArray(order) ? order : [];
        if (axis === "column") {
            let y = 0;
            for (const n of list) {
                map[n] = U.fmtPos(0, y);
                y += settings.effSize(n).h;
            }
        } else {
            let x = 0;
            for (const n of list) {
                map[n] = U.fmtPos(x, 0);
                x += settings.effSize(n).w;
            }
        }
        return map;
    }
    function setMonitorLayout(map: var): void {
        const names = map ? Object.keys(map) : [];
        if (names.length === 0)
            return;
        const targets = [];
        for (const n of names) {
            if (settings.monitorLive(n) === null)
                continue;
            if (typeof map[n] !== "string" || settings.monitorPos(n) === map[n])
                continue;
            settings.putMonitorCfg(n, {pos: map[n]});
            targets.push(n);
        }
        if (targets.length === 0)
            return;
        settings.applyMonitorRules(targets, targets.join(", ") + " arranged");
        settings.scheduleSave();
    }
    function layoutAxis(): string {
        const live = settings.enabledMonitors();
        if (live.length < 2)
            return "row";
        let minX = 1e9, maxX = -1e9, minY = 1e9, maxY = -1e9;
        for (const m of live) {
            const x = m.x ?? 0, y = m.y ?? 0;
            if (x < minX)
                minX = x;
            if (x > maxX)
                maxX = x;
            if (y < minY)
                minY = y;
            if (y > maxY)
                maxY = y;
        }
        return (maxY - minY) > (maxX - minX) ? "column" : "row";
    }
    function reflowPositions(): var {
        const enabled = settings.enabledMonitors().filter(m => m && settings.monitorLive(m.name) !== null);
        if (enabled.length < 2)
            return {moved: [], map: {}};
        const axis = settings.layoutAxis();
        const byAxis = axis === "column" ? (a, b) => (a.y ?? 0) - (b.y ?? 0) : (a, b) => (a.x ?? 0) - (b.x ?? 0);
        const order = enabled.slice().sort(byAxis).map(m => String(m.name));
        const map = settings.layoutCoords(order, axis);
        const moved = [];
        for (const n of order) {
            if (typeof map[n] !== "string" || settings.monitorPos(n) === map[n])
                continue;
            settings.putMonitorCfg(n, {pos: map[n]});
            moved.push(n);
        }
        return {moved: moved, map: map};
    }
    function applyMonitorRules(names: var, label: string): var {
        const seen = {};
        const list = [];
        for (const n of (Array.isArray(names) ? names : [])) {
            if (typeof n !== "string" || n === "" || seen[n])
                continue;
            seen[n] = true;
            list.push(n);
        }
        if (list.length === 0)
            return [];
        const coords = list.map(n => ({n: n, p: U.parsePos(settings.monitorPos(n)) ?? {x: 0, y: 0}}));
        coords.sort((a, b) => a.p.x - b.p.x || a.p.y - b.p.y);
        const ordered = coords.map(c => c.n);
        settings.applyBatched(label !== "" ? label : ordered.join(", ") + " arranged", ordered.map(n => settings.monitorRuleCode(n)), false, ordered);
        return ordered;
    }
    function applyWithReflow(name: string, changed: bool): void {
        const moved = settings.reflowPositions().moved;
        if (!changed && moved.length === 0) {
            settings.applyMonitor(name);
        } else if (moved.length === 0) {
            settings.applyMonitorRules([name], settings.monitorRuleDesc(name));
        } else {
            const targets = moved.includes(name) ? moved : [...moved, name];
            settings.applyMonitorRules(targets, targets.join(", ") + " arranged");
        }
        settings.scheduleSave();
    }
    function revertCfgToLive(name: string): void {
        const live = settings.monitorLive(name);
        if (!live)
            return;
        const patch = {};
        patch.enabled = live.disabled !== true;
        if (typeof live.scale === "number" && !isNaN(live.scale))
            patch.scale = Math.max(0.5, Math.min(3, live.scale));
        const mode = U.liveModeStr(live);
        if (mode !== "")
            patch.res = mode;
        if (typeof live.x === "number" && typeof live.y === "number")
            patch.pos = U.fmtPos(live.x, live.y);
        settings.putMonitorCfg(name, patch);
        settings.scheduleSave();
    }
    function applyTracked(label: string, code: string, quiet: bool, key: string): void {
        const k = typeof key === "string" && key !== "" ? key : label;
        settings.applyQueue = [...settings.applyQueue.filter(j => j.key !== k), {label: label, code: code, quiet: !!quiet, key: k}];
        if (settings.applyQueue.length > 20)
            settings.applyQueue = settings.applyQueue.slice(settings.applyQueue.length - 20);
        settings.pumpApply();
    }
    function applyBatched(label: string, codes: var, quiet: bool, keys: var): void {
        const list = Array.isArray(codes) ? codes.slice() : [];
        const names = Array.isArray(keys) ? keys.slice() : [];
        if (list.length === 0 || names.length === 0)
            return;
        const k = names.join(",");
        settings.applyQueue = [...settings.applyQueue.filter(j => j.key !== k), {label: label, codes: list, quiet: !!quiet, key: k, batch: true}];
        if (settings.applyQueue.length > 20)
            settings.applyQueue = settings.applyQueue.slice(settings.applyQueue.length - 20);
        settings.pumpApply();
    }
    function pumpApply(): void {
        if (monApply.running || settings.applyQueue.length === 0)
            return;
        const job = settings.applyQueue[0];
        settings.applyQueue = settings.applyQueue.slice(1);
        monApply.jobLabel = job.label;
        monApply.jobQuiet = job.quiet;
        monApply.jobKey = job.key;
        monApply.jobBatch = job.batch === true;
        if (monApply.jobBatch)
            monApply.command = ["hyprctl", "--batch", job.codes.map(c => "eval " + c).join(" ; ")];
        else
            monApply.command = ["hyprctl", "eval", job.code];
        monApply.running = true;
        applyTimeout.restart();
    }
    function putMonitorCfg(name: string, patch: var): void {
        const cfgs = Object.assign({}, settings.monitorConfigs);
        cfgs[name] = Object.assign({}, settings.monitorCfg(name), patch);
        settings.monitorConfigs = cfgs;
    }
    function scaleDims(name: string): var {
        const cfg = settings.monitorCfg(name);
        if (cfg && typeof cfg.res === "string" && cfg.res !== "" && cfg.res !== "preferred") {
            const p = U.parseMode(cfg.res);
            if (p.valid && p.w > 0 && p.h > 0)
                return {w: p.w, h: p.h};
        }
        const live = settings.monitorLive(name);
        return {w: live && typeof live.width === "number" ? live.width : 1920, h: live && typeof live.height === "number" ? live.height : 1080};
    }
    function setMonitorScale(name: string, v: real): void {
        const d = settings.scaleDims(name);
        const snapped = U.nearestValidScale(d.w, d.h, Math.max(0.5, Math.min(3, v)));
        const rounded = Math.round(snapped * 20) / 20;
        const prev = settings.monitorScale(name);
        settings.putMonitorCfg(name, {scale: rounded});
        settings.applyWithReflow(name, rounded !== prev);
    }
    function cycleValidScale(name: string, dir: int): void {
        if (typeof name !== "string" || name === "")
            return;
        const d = settings.scaleDims(name);
        settings.setMonitorScale(name, U.nextValidScale(d.w, d.h, settings.monitorScale(name), dir));
    }
    function setMonitorEnabled(name: string, on: bool): void {
        if (!on && !settings.canDisableMonitor(name)) {
            settings.lastApplyMsg = "Cannot disable " + name + " (only display)";
            return;
        }
        settings.putMonitorCfg(name, {enabled: on});
        if (!on && settings.mainMonitor === name)
            settings.mainMonitor = "auto";
        settings.applyWithReflow(name, true);
    }
    function setMonitorRes(name: string, res: string): void {
        const prevRes = settings.monitorRes(name);
        settings.putMonitorCfg(name, {res: res});
        settings.applyWithReflow(name, prevRes !== res);
    }
    function setMonitorResolution(name: string, resKey: string): void {
        if (typeof name !== "string" || name === "")
            return;
        if (resKey === "Preferred") {
            settings.setMonitorRes(name, "preferred");
            return;
        }
        const fulls = U.ratesForMode(settings.monitorModes(name), resKey);
        if (fulls.length === 0) {
            settings.lastApplyMsg = "No mode for " + resKey + " on " + name;
            return;
        }
        settings.setMonitorRes(name, fulls[0]);
    }
    function cycleMonitorResolution(name: string, dir: int): void {
        const opts = settings.monitorResolutions(name);
        settings.setMonitorResolution(name, U.cycleOpt(opts, settings.monitorResKey(name), dir));
    }
    function setMonitorPos(name: string, pos: string): void {
        if (!U.isValidMonitorPos(pos))
            return;
        settings.putMonitorCfg(name, {pos: pos});
        settings.applyMonitor(name, false, true);
        settings.scheduleSave();
    }
    function cycleMonitorPos(name: string, dir: int): void {
        settings.setMonitorPos(name, U.cycleOpt(U.monitorPosOptions(), settings.monitorPos(name), dir));
    }

    property var monitors: []
    property var monitorConfigs: ({})
    property string mainMonitor: "auto"
    function mainMonitorOptions(): var {
        const names = settings.enabledMonitors().map(m => String(m && m.name ? m.name : "")).filter(n => n !== "");
        return ["auto"].concat(names);
    }
    function setMainMonitor(name: string): void {
        let next = (typeof name === "string" && name !== "") ? name : "auto";
        if (next !== "auto" && settings.monitorsReady) {
            const live = settings.monitorLive(next);
            if (!live || !settings.monitorEnabled(next))
                next = "auto";
        }
        settings.mainMonitor = next;
        settings.scheduleSave();
    }
    function mainScreen(screens, focusedName): var {
        const list = screens ?? [];
        const want = settings.mainMonitor;
        if (typeof want === "string" && want !== "" && want !== "auto" && settings.monitorEnabled(want)) {
            const hit = list.find(s => s && s.name === want);
            if (hit)
                return hit;
        }
        return list.length > 0 ? list[0] : null;
    }
    function popupScreen(screens, focusedName): var {
        const list = screens ?? [];
        if (typeof focusedName === "string" && focusedName !== "") {
            const fhit = list.find(s => s && s.name === focusedName);
            if (fhit)
                return fhit;
        }
        return settings.mainScreen(list, focusedName);
    }
    property bool monitorsReady: false
    property var appliedMonitors: []

    function setDimTimeout(v: real): void {
        settings.dimTimeout = Math.round(Math.max(0, Math.min(600, v)));
        settings.writeIdleConf();
        settings.scheduleSave();
    }
    function setLockTimeout(v: real): void {
        settings.lockTimeout = Math.round(Math.max(0, Math.min(3600, v)));
        settings.enforceIdleOrder();
        settings.writeIdleConf();
        settings.scheduleSave();
    }
    function setScreenOffTimeout(v: real): void {
        settings.screenOffTimeout = Math.round(Math.max(0, Math.min(3600, v)));
        settings.enforceIdleOrder();
        settings.writeIdleConf();
        settings.scheduleSave();
    }
    function setSuspendTimeout(v: real): void {
        settings.suspendTimeout = Math.round(Math.max(0, Math.min(7200, v)));
        settings.enforceIdleOrder();
        settings.writeIdleConf();
        settings.scheduleSave();
    }
    function enforceIdleOrder(): void {
        if (settings.lockTimeout > 0) {
            if (settings.screenOffTimeout > 0 && settings.screenOffTimeout < settings.lockTimeout)
                settings.screenOffTimeout = settings.lockTimeout;
            if (settings.suspendTimeout > 0 && settings.suspendTimeout < settings.screenOffTimeout && settings.screenOffTimeout > 0)
                settings.suspendTimeout = settings.screenOffTimeout;
            if (settings.suspendTimeout > 0 && settings.screenOffTimeout === 0 && settings.suspendTimeout < settings.lockTimeout)
                settings.suspendTimeout = settings.lockTimeout;
        }
    }
    function setLowBatteryPct(v: real): void {
        settings.lowBatteryPct = Math.round(Math.max(5, Math.min(50, v)));
        if (settings.criticalBatteryPct > settings.lowBatteryPct)
            settings.criticalBatteryPct = settings.lowBatteryPct;
        settings.scheduleSave();
    }
    function setCriticalBatteryPct(v: real): void {
        settings.criticalBatteryPct = Math.min(Math.round(Math.max(3, Math.min(30, v))), settings.lowBatteryPct);
        settings.scheduleSave();
    }
    function setLidCloseAction(v: string): void {
        if (!["suspend", "lock", "ignore"].includes(v))
            return;
        if (settings.lidCloseAction === v)
            return;
        settings.lidCloseAction = v;
        settings.scheduleSave();
        settings.promptLidApply(v);
    }
    function promptLidApply(v: string): void {
        Notifs.notify({app: "settings", summary: "Lid close → " + v, body: "Click to install into logind (needs root). Reboot to take effect.", syncId: "lid-apply", timeout: 15000, actions: [{identifier: "default", text: "Apply", invoke: () => settings.applyLidSwitch(v)}]});
    }
    function applyLidSwitch(v: string): void {
        if (!["suspend", "lock", "ignore"].includes(v))
            return;
        lidApply.command = ["sh", "-c", 'for c in "$HOME/.local/bin/qs-power-logind" "$HOME/dotfiles/bin/qs-power-logind"; do [ -x "$c" ] && exec pkexec "$c" --install "$1"; done; exit 99', "qs", v];
        lidApply.running = true;
    }
    function setPowerProfileOnBattery(v: string): void {
        if (!["keep", "powersaver", "balanced", "performance"].includes(v))
            return;
        settings.powerProfileOnBattery = v;
        settings.scheduleSave();
    }
    function writeIdleConf(): void {
        IdleManager.request(settings.dimTimeout, settings.lockTimeout, settings.screenOffTimeout, settings.suspendTimeout, settings.hypridleFile);
    }

    property bool saveQueued: false
    function scheduleSave(): void {
        if (!settings.loaded)
            return;
        settings.saveQueued = true;
        saveTimer.restart();
    }
    Timer {
        id: saveTimer
        interval: 800
        repeat: false
        onTriggered: {
            if (!settings.saveQueued)
                return;
            if (saver.running)
                return;
            settings.saveQueued = false;
            saver.command = ["sh", "-c", 'mkdir -p "$(dirname "$2")"; printf "%s\\n" "$1" > "$2.tmp"; mv -f "$2.tmp" "$2"; mkdir -p "$(dirname "$4")"; printf "%s\\n" "$3" > "$4.tmp"; mv -f "$4.tmp" "$4"', "qs", JSON.stringify(settings.snapshot()), settings.settingsFile, settings.monitorsLua(), settings.monitorsLuaFile];
            saver.running = true;
        }
    }
    Process {
        id: saver
        onExited: exitCode => {
            if (exitCode !== 0) {
                settings.saveQueued = true;
                saveTimer.restart();
            } else if (settings.saveQueued) {
                saveTimer.restart();
            }
        }
    }
    Process {
        id: lidApply
        onExited: exitCode => {
            if (exitCode === 0)
                Notifs.notify({app: "settings", summary: "Lid action installed", body: "Reboot for logind to pick it up.", syncId: "lid-apply", timeout: 8000});
            else
                Notifs.notify({app: "settings", summary: "Lid install cancelled/failed", body: "Run qs-power-logind --apply in a terminal.", syncId: "lid-apply", timeout: 8000});
        }
    }
    Process {
        id: loader
        property bool loadDone: false
        command: ["cat", settings.settingsFile]
        stdout: StdioCollector {
            onStreamFinished: {
                if (loader.loadDone)
                    return;
                loader.loadDone = true;
                let parsed = null;
                let corrupt = false;
                try {
                    parsed = JSON.parse(text);
                } catch (_) {
                    corrupt = text.trim() !== "";
                }
                if (!corrupt && parsed !== null && (typeof parsed !== "object" || Array.isArray(parsed)))
                    corrupt = true;
                if (corrupt) {
                    console.warn("quickshell: settings.json corrupt, keeping defaults; backup at settings.json.corrupt-" + Date.now());
                    Quickshell.execDetached(["sh", "-c", 'cp "$1" "$1.corrupt-$(date +%s%3N)" 2>/dev/null', "qs", settings.settingsFile]);
                    Notifs.notify({app: "settings", summary: "Settings file corrupt, defaults kept", body: "Backup saved next to settings.json", syncId: "settings-load", timeout: 8000});
                } else {
                    settings.applyLoaded(parsed);
                }
                settings.loaded = true;
                settings.applyAll();
                settings.refreshWallpapers(true);
                settings.applyScannedMonitors();
            }
        }
        onExited: exitCode => {
            if (loader.loadDone)
                return;
            loader.loadDone = true;
            if (exitCode !== 0) {
                settings.loaded = true;
                settings.applyAll();
                settings.refreshWallpapers(true);
            }
        }
        Component.onCompleted: loader.running = true
    }
    Process {
        id: wallpaperScan
        command: ["sh", "-c", "for d in \"$HOME/dotfiles/wallpapers\" \"$HOME/Pictures/Wallpapers\"; do [ -d \"$d\" ] && find \"$d\" -maxdepth 1 -type f \\( -iname '*.jpg' -o -iname '*.jpeg' -o -iname '*.png' -o -iname '*.webp' \\) 2>/dev/null; done | awk '!s[$0]++' | head -n 200 | { while IFS= read -r f; do k=$(stat -c '%d:%i:%s' \"$f\" 2>/dev/null) || k=\"0:0:0\"; echo \"$k $f\"; done; } | awk '!s[$1]++ {print substr($0,length($1)+2)}' | sort | head -n 100"]
        stdout: StdioCollector {
            onStreamFinished: {
                settings.wallpapers = text.trim().split("\n").filter(s => s !== "");
                settings.ensureWallpaper();
            }
        }
        onExited: exitCode => {
            if (exitCode !== 0)
                settings.wallpapers = [];
        }
    }
    Process {
        id: monitorScan
        command: ["hyprctl", "monitors", "all", "-j"]
        stdout: StdioCollector {
            onStreamFinished: {
                try {
                    const arr = JSON.parse(text);
                    settings.monitors = Array.isArray(arr) ? arr : [];
                } catch (_) {
                    settings.monitors = [];
                }
                const live = {};
                for (const m of settings.monitors) {
                    if (m && typeof m.name === "string" && m.name !== "")
                        live[m.name] = true;
                }
                settings.appliedMonitors = settings.appliedMonitors.filter(n => live[n]);
                if (settings.monitors.length > 0 && settings.mainMonitor !== "auto" && (!live[settings.mainMonitor] || !settings.monitorEnabled(settings.mainMonitor))) {
                    settings.mainMonitor = "auto";
                    settings.scheduleSave();
                }
                settings.monitorsReady = true;
                settings.applyScannedMonitors();
            }
        }
        onExited: exitCode => {
            if (exitCode !== 0) {
                settings.monitors = [];
                settings.monitorsReady = true;
                settings.applyScannedMonitors();
            }
        }
        Component.onCompleted: monitorScan.running = true
    }
    Process {
        id: monApply
        property string jobLabel: ""
        property bool jobQuiet: false
        property string jobKey: ""
        property bool jobBatch: false
        property bool dropNextExit: false
        stdout: StdioCollector {
            id: monOut
        }
        stderr: StdioCollector {
            id: monErr
        }
        onExited: exitCode => {
            if (monApply.dropNextExit) {
                monApply.dropNextExit = false;
                settings.pumpApply();
                return;
            }
            applyTimeout.stop();
            const detail = (monErr.text + " " + monOut.text).trim();
            const failed = exitCode !== 0;
            if (!failed) {
                settings.lastApplyMsg = monApply.jobLabel + " applied";
            } else {
                settings.lastApplyMsg = "Failed: " + monApply.jobLabel + (detail !== "" ? " (" + detail.slice(0, 120) + ")" : "");
                const keys = monApply.jobBatch ? String(monApply.jobKey ?? "").split(",").filter(k => k !== "") : [monApply.jobKey];
                let reverted = false;
                for (const key of keys) {
                    if (typeof key === "string" && key !== "" && settings.monitorLive(key) !== null) {
                        settings.revertCfgToLive(key);
                        reverted = true;
                    }
                }
                if (reverted) {
                    settings.refreshMonitors(true);
                    Notifs.notify({app: "settings", summary: "Display change reverted", body: monApply.jobLabel + " was rejected; restored last working mode.", syncId: "display-revert", timeout: 8000});
                }
            }
            settings.pumpApply();
            if (!monApply.running)
                settings.refreshMonitors(true);
        }
    }
    Timer {
        id: applyTimeout
        interval: 10000
        repeat: false
        onTriggered: {
            if (monApply.running) {
                monApply.running = false;
                monApply.dropNextExit = true;
                settings.lastApplyMsg = "Timed out: " + monApply.jobLabel;
            }
        }
    }
}
