general {
    lock_cmd = qs ipc call bar lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl eval 'hl.dispatch(hl.dsp.dpms("on"))'
}

listener {
    timeout = 150
    on-timeout = [ "$(brightnessctl g)" -gt 2500 ] && brightnessctl -s set 3%; hyprctl hyprsunset gamma 50
    on-resume = brightnessctl -r; hyprctl hyprsunset gamma 100
}

listener {
    timeout = 150
    on-timeout = brightnessctl -sd '*:kbd_backlight' set 0
    on-resume = brightnessctl -rd '*:kbd_backlight'
}

listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330
    on-timeout = hyprctl eval 'hl.dispatch(hl.dsp.dpms("off"))'
    on-resume = hyprctl eval 'hl.dispatch(hl.dsp.dpms("on"))'
}

listener {
    timeout = 1800
    on-timeout = systemctl suspend
}

