font_family JetBrainsMono Nerd Font Mono
font_size 11.0

background #000000
foreground #ffffff
cursor #ffffff
selection_background #ffffff
selection_foreground #000000
cursor_text_color #000000

url_color #ffffff
active_border_color #ffffff
inactive_border_color #333333
bell_border_color #ffffff

hide_window_decorations no
window_padding_width 10

cursor_shape block
cursor_blink_interval 0

scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT

copy_on_select clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

tab_bar_style powerline
tab_bar_margin_width 4

background_opacity 1.0
dynamic_background_opacity no

shell_integration enabled
