font_family JetBrainsMono Nerd Font Mono
font_size 11.0

# vague palette (vague-theme/vague-kitty)
foreground #cdcdcd
background #141415
selection_foreground #cdcdcd
selection_background #252530
cursor none
url_color #bb9dbd

color0 #252530
color1 #d8647e
color2 #7fa563
color3 #f3be7c
color4 #6e94b2
color5 #bb9dbd
color6 #aeaed1
color7 #cdcdcd
color8 #606079
color9 #e08398
color10 #99b782
color11 #f5cb96
color12 #8ba9c1
color13 #c9b1ca
color14 #bebeda
color15 #d7d7d7

active_border_color #878787
inactive_border_color #252530
bell_border_color #f3be7c

active_tab_foreground #cdcdcd
active_tab_background #252530
inactive_tab_foreground #606079
inactive_tab_background #141415

hide_window_decorations no
window_padding_width 10

cursor_shape block
cursor_blink_interval 0

scrollback_lines 10000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT

copy_on_select clipboard
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

tab_bar_style powerline
tab_bar_margin_width 4

background_opacity 1.0
dynamic_background_opacity no

shell_integration enabled
